### ISSUE TITLE
yarn install not working

### ISSUE THREAD

**Issue by Panda260** [kacesensitive/ollama-discord#2]
Hey

i tries to install the bot and run into a error while trying to run `yarn install` iget the following error: `00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install`

i have the following files in the directory:
`Modelfile` `README.md`  `example.png`  `jest.config.js`  `ollama-discord.png`  `package.json`  `renameImport.cjs`  `src`  `test.gif`  `tsconfig.json`  `yarn.lock`

**Comment by kacesensitive** [comment]
@Panda260 can you run

`yarn --version`

Also send a screenshot of what you are running when it fails.

**Comment by Panda260** [comment]
![Termius_unzuluSW0E](https://github.com/kacesensitive/ollama-discord/assets/52088459/17642a27-6b34-48d5-a700-0dec44bcc42b)
i did apt install yarn

**Comment by kacesensitive** [comment]
It is recommended to install Yarn through the npm package manager, which comes bundled with Node.js when you install it on your system.

https://classic.yarnpkg.com/lang/en/docs/install

Closing this as it is a problem with your installation not the repo, but feel free to comment here if you need further help

**Comment by Panda260** [comment]
i get this error all the time:

```
root@docker:/home/ollama-discord# yarn start
yarn run v1.22.22
$ yarn build && node dist/index.js
$ tsc && node renameImport.cjs
Ollama Online! Ready to receive messages preceded by !ai
Making request to 192.168.178.27:11434 with model mistral with prompt hey
Ollama request failed, is Ollama running?) Error: XMLHttpRequest is not defined
```

```
DISCORD_BOT_TOKEN=
CHANNELIDS=
OLLAMAURL=192.168.178.27:11434
CUSTOMMODEL=mistral
TRIGGER=!ai
```

![image](https://github.com/kacesensitive/ollama-discord/assets/52088459/2f942202-8960-4793-918c-996ecc0dbb2d)


the docker-compose from my setp ollama works also with the webui:
```
version: '3.8'
services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - 11434:11434
    image: ollama/ollama:latest

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3005}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
  ```
