### ISSUE TITLE
 XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by Panda260** [kacesensitive/ollama-discord#3]
i get this error all the time:

```
root@docker:/home/ollama-discord# yarn start
yarn run v1.22.22
$ yarn build && node dist/index.js
$ tsc && node renameImport.cjs
Ollama Online! Ready to receive messages preceded by !ai
Making request to 192.168.178.27:11434 with model mistral with prompt hey
Ollama request failed, is Ollama running?) Error: XMLHttpRequest is not defined
```

```
DISCORD_BOT_TOKEN=
CHANNELIDS=
OLLAMAURL=192.168.178.27:11434
CUSTOMMODEL=mistral
TRIGGER=!ai
```

![image](https://github.com/kacesensitive/ollama-discord/assets/52088459/2f942202-8960-4793-918c-996ecc0dbb2d)

the docker-compose from my setp ollama works also with the webui:
```
version: '3.8'
services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - 11434:11434
    image: ollama/ollama:latest

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3005}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
  ```
